version: "3"
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    networks:
      - nginx-network
    depends_on:
      - nginx
    volumes:
      - ./conf:/mosquitto/conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log


networks:
  default:
    external: true
    name: nginx-network